.TH NAVIPAGE 1 navipage\-VERSION

.SH NAME
navipage \- multi-file pager for watching YouTube videos

.SH SYNOPSIS
.B navipage
.RB [ \-dhnrsv ]
.RI [ files ...]

.SH DESCRIPTION
.B navipage
is a multi-file pager with features to streamline watching YouTube videos which
are linked in a file.
.PP
.I NOTE:
.B navipage
is in an early stage of development. It may have bugs, and the documentation
may at times be outdated or inaccurate. Do not use
.B navipage
if you expect otherwise.

.SH OPTIONS
.TP
.B \-d
Enable debug output.
.TP
.B \-h
Print usage information and exit.
.TP
.B \-n
Display line numbers.
.TP
.B \-r
Infinitely recurse in directories.
.TP
.B \-s
Run
.B $NAVIPAGE_SH
before reading files.
.TP
.B \-v
See -h.

.SH USAGE
.B navipage
is a pager, which means its primary function is to view files.
.PP
On startup,
.B navipage
will read all of the
.I files
passed as arguments into buffers, unless a file is a directory, in which case
it will read all of the files in that directory. It will not go into
directories within that directory unless the
.B \-r
option is specified.
.PP
If
.B \-s
was specified and
.B $NAVIPAGE_SH
is set, then that file will be ran as a shell script before files are read. See
below for an example.
.PP
If
.B $NAVIPAGE_DIR
is set, then all the files in that directory will be read, as if they were
passed as arguments and
.B \-r
was set.
.PP
.BR navipage "'s"
key bindings are simple and few, and will be familiar to anyone who's used
the popular *NIX programs
.BR "less" "(1) or " "vi" "(1)."
.TP
.B g
Scroll to the top of the file.
.TP
.B G
Scroll to the bottom of the file.
.TP
.B h
Move one buffer to the left.
.TP
.B H
Move to the first buffer.
.TP
.B i
Display help information (through
.BR "man navipage" )
.TP
.B j / MouseDown
Scroll down one line.
.TP
.B k / MouseUp
Scroll up one line.
.TP
.B l
Move one buffer to the right.
.TP
.B L
Move to the last buffer.
.TP
.B q
Quit
.BR navipage .
.TP
.B !
Execute a command with sh.
.SH EXAMPLES
.EX
#!/bin/sh

# This is an example of what your $NAVIPAGE_SH could look like.

# Compares the files stored on a server with the files stored locally. Any
# files that are found only once (and are therefore only on the server) are
# formatted into a list and copied with scp.

# On my own server, there is a user that runs omnavi on a cronjob every
# morning. A variation on this script is how I get updates on my own machine
# every day.

# Of course, you can just as well run Omnavi on your own local machine, but I
# like getting the update automatically every morning without having to wait
# the five minutes or so it takes for it to run. Also, I used to read my new
# videos every morning by an email, which is easier to send when ran on the
# server where the email is hosted.

server="user@example.notreal"
serverdir="backups"

( ssh "$server" ls -1 "$serverdir"; ls -1 $NAVIPAGE_DIR )\\
	| sort | uniq -u | sed "s/^/$serverdir\//" | tr '\\n' ' '\\
	| sed 's/^/"/;s/$/"/;'\\
	| xargs -I '{}' scp -T "$server":'{}' "$NAVIPAGE_DIR"
.EE
.SH INSPIRATION
My original plan with
.B omnavi
was to receive an email every morning with my YouTube subscriptions. This works
reasonably well, however it is not perfect.  In particular, it is too
cumbersome to see videos that were uploaded on previous days (this requires
searching through past emails), and it is too cumbersome to save videos to
watch for later.
.B navipage
makes it easier to search for particular creators or videos, and quickly look
through multiple days worth of videos.

.SH AUTHOR
Written by Sebastian LaVine.

.SH COPYRIGHT
Copyright (C) 2021 Sebastian LaVine <mail@smlavine.com>
.PP
navipage is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
navipage is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with navipage. If not, see <https://www.gnu.org/licenses/>.

.SH LIBRARIES
.B navipage
makes use of the following libraries:
.TP
.B GNU readline
.I https://tiswww.case.edu/php/chet/readline/rltop.html
.TP
.B rogueutil
.I https://github.com/sakhmatd/rogueutil

.SH QUESTIONS, QUERIES, POSERS, CONCERNS, THINGS THAT HAUNT YOU IN THE NIGHT
To discuss
.BR navipage ,
suggest features, or report bugs, use the public mailling list at
.IR https://lists.sr.ht/~smlavine/navipage .

.SH SEE ALSO
.TP
.RB "For more information on " "navipage" ", see"
.IR https://sr.ht/~smlavine/navipage .
.PP
.TP
.RB "For information on the companion project " "omnavi" ", see"
.IR https://sr.ht/~smlavine/omnavi .
