.TH NAVIPAGE 1 navipage\-VERSION
.SH NAME
navipage \- multi-file pager for watching YouTube videos
.SH SYNOPSIS
.B navipage
.RB [ \-dhrv ]
.RI [ files ...]
.SH DESCRIPTION
.B navipage
is a multi-file pager with features to streamline watching YouTube videos which
are linked in a file.
.PP
.I NOTE:
.B navipage
is in an early stage of development. It may have bugs, and the documentation
may at times be outdated or inaccurate. Do not use
.B navipage
if you expect otherwise.
.SH OPTIONS
.TP
.B \-d
Enable debug output.
.TP
.B \-h
Print usage information and exit.
.TP
.B \-r
Infinitely recurse in directories.
.TP
.B \-v
Print version and exit.
.SH INSPIRATION
My original plan with
.B omnavi
was to receive an email every morning with my YouTube subscriptions. This works
reasonably well, however it is not perfect.  In particular, it is too
cumbersome to see videos that were uploaded on previous days (this requires
searching through past emails), and it is too cumbersome to save videos to
watch for later.
.B navipage
makes it easier to search for particular creators or videos, and quickly look
through multiple days worth of videos.
.SH AUTHOR
Written by Sebastian LaVine.
.SH COPYRIGHT
Copyright (C) 2021 Sebastian LaVine <mail@smlavine.com>

navipage is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

navipage is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with navipage. If not, see <https://www.gnu.org/licenses/>.

.SH SEE ALSO
For more recent information on
.BR navipage ,
see <https://github.com/smlavine/navipage>.

For information on the companion project
.BR omnavi ,
see <https://github.com/smlavine/omnavi>.
